api:
  - .github/workflows/ci_cd.yml
  - api/**
ingestion_server:
  - .github/workflows/ci_cd.yml
  - ingestion_server/**
frontend:
  - .github/workflows/ci_cd.yml
  - frontend/**
  - package.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - .npmrc
  - .pnpmfile.cjs
