# This file assigns names to groups of files. These names can be used to
# determine which stacks have changed, which in turn is used to
# - apply labels to PRs (see workflows `label_new_pr.yml` and `label_pr.yml`)
# - determine which tests to run in CI (see workflow `ci_cd.yml`)

workflows:
  - .github/workflows/**
workflow_ci_cd:
  - .github/workflows/ci_cd.yml
workflow_bundle_size:
  - .github/workflows/bundle_size.yml
api:
  - api/**
ingestion_server:
  - ingestion_server/**
frontend:
  - frontend/**
  - package.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - .npmrc
  - .pnpmfile.cjs
documentation:
  - documentation/**
lint:
  - prettier.config.js
  - .prettierignore
  - .eslintrc.js
  - .eslintignore
  - .pre-commit-config.yaml
