# Also see list of stacks in the job `add-stack-label` under workflow
# `.github/workflows/ci_cd.yml`.
catalog:
  - catalog/**
  - docker/minio/**
  - docker/upstream_db/**
api:
  - api/**
  - docker/db/**
  - docker/es/**
  - docker/nginx/**
  - load_sample_data.sh
ingestion_server:
  - ingestion_server/**
  - docker/db/**
  - docker/es/**
  - docker/upstream_db/**
  - load_sample_data.sh
frontend:
  - frontend/**
  - package.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - tsconfig.json
  - .npmrc
  - .pnpmfile.cjs
analytics:
  - docker/clickhouse/**
  - docker/plausible/**
  - docker/plausible_db/**
  - setup_plausible.sh
documentation:
  - documentation/**
lint:
  - prettier.config.js
  - .editorconfig
  - .eslintrc.js
  - .eslintignore
  - .isort.cfg
  - .ruff.toml
  - .prettierignore
  - .pre-commit-config.yaml
mgmt:
  - .github/**
  - automations/**
ci_cd:
  - .github/workflows/ci_cd.yml
