# yaml-language-server: $schema=https://raw.githubusercontent.com/release-drafter/release-drafter/master/schema.json
#
# Configuration for the action `release-drafter/release-drafter`
# Docs: https://github.com/release-drafter/release-drafter
# Workflow: Draft release

name-template: "API $RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: New Features
    label: "🌟 goal: addition"
  - title: Improvements
    label: "✨ goal: improvement"
  - title: Internal Improvements
    labels:
      - "🤖 aspect: dx"
      - "🧰 goal: internal improvement"
  - title: Bug Fixes
    label: "🛠 goal: fix"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
include-labels:
  - "🧱 stack: api"
exclude-labels:
  - "skip-changelog"
template: |
  $CHANGES

  ## Credits

  Thanks to $CONTRIBUTORS for their contributions!
