name: openverse/build-docs
description: Build Openverse full-stack docs

inputs:
  glotpress_username:
    required: true
    description: The username for the GlotPress account for bulk download

  glotpress_password:
    required: true
    description: The password for the GlotPress account for bulk download

runs:
  using: "composite"
  steps:
    - name: Build Sphinx
      shell: bash
      run: |
        just documentation/build

    - name: Install translations
      shell: bash
      run: |
        just frontend/run i18n
      env:
        GLOTPRESS_USERNAME: ${{ inputs.glotpress_username }}
        GLOTPRESS_PASSWORD: ${{ inputs.glotpress_password }}

    - name: Build Storybook
      shell: bash
      run: |
        just frontend/run storybook:build

    - name: Build Tailwind Config Viewer
      shell: bash
      run: |
        just frontend/run tcv:build

    - name: Load Docker images # For API schema
      uses: ./.github/actions/load-img
      with:
        setup_images: '["upstream_db", "ingestion_server", "api"]'

    - name: Build Redoc
      shell: bash
      run: |
        just api/doc-test
        mv api/openapi.json api/api_docs
      env:
        DC_USER: root

    # Storybook will be available at `/storybook`
    # Tailwind will be available at `/tailwind`
    - name: Merge all docs
      shell: bash
      run: |
        mv documentation/_build /tmp/docs
        mv frontend/storybook-static /tmp/docs/storybook
        mv frontend/.tcv-export /tmp/docs/tailwind
        mv api/api_docs /tmp/docs/api_docs
