version: '3'

services:
  control:
    build: .
    image: locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/${LOCUSTFILE} --master -H ${HOST} ${ARGS}
  
  worker-0:
    build: .
    image: locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/${LOCUSTFILE} --worker --master-host control

  worker-1:
    build: .
    image: locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/${LOCUSTFILE} --worker --master-host control

  worker-2:
    build: .
    image: locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/${LOCUSTFILE} --worker --master-host control

  worker-3:
    build: .
    image: locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/${LOCUSTFILE} --worker --master-host control
