name: New discussion notification
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#new-discussion-notification

on:
  discussion:
    types:
      - created

jobs:
  send_message:
    name: Send Slack message
    runs-on: ubuntu-latest
    env:
      slack_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      discussion_url: ${{ github.event.discussion.html_url }}
      discussion_number: ${{ github.event.discussion.number }}
      discussion_title: ${{ github.event.discussion.title }}
      discussion_author: ${{ github.event.discussion.user.login }}
      discussion_repo: ${{ github.event.repository.full_name }}
    steps:
      - name: Send notification for new discussion
        id: slack
        uses: slackapi/slack-github-action@1.23.0
        with:
          payload: |
            {"text": "New discussion opened by '$discussionAuthor' in '$discussionRepo': #$discussionNumber - '$discussionTitle'", "blocks": [{"type": "section", "text": {"type": "mrkdwn", "text": ":github: New discussion opened by *'$discussionAuthor'* in '`$discussionRepo`':\n<$discussionUrl|#$discussionNumber - '$discussionTitle'>"}}]}