name: PR label check
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#pr-label-check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_aspect_label:
    name: Check aspect label
    runs-on: ubuntu-latest
    steps:
      - name: Check aspect label
        uses: agilepathway/label-checker@v1.2.9
        with:
          any_of: api,bug,build,dependencies,documentation,enhancement,no-changelog,refactoring

  check_goal_label:
    name: Check goal label
    runs-on: ubuntu-latest
    steps:
      - name: Check goal label
        uses: agilepathway/label-checker@v1.2.9
        with:
          any_of: api,bug,build,dependencies,documentation,enhancement,no-changelog,refactoring

  check_priority_label:
    name: Check priority label
    runs-on: ubuntu-latest
    steps:
      - name: Check priority label
        uses: agilepathway/label-checker@v1.2.9
        with:
          any_of: api,bug,build,dependencies,documentation,enhancement,no-changelog,refactoring
