name: PR Limit Reminders

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

jobs:
  analyze-user-prs:
    name: Count user's open pull requests
    runs-on: ubuntu-latest
    outputs:
      pr_count: ${{ steps.count-prs.outputs.pr_count }}
      slack_id: ${{ steps.count-prs.outputs.slack_id }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v6
        id: count-prs
        env:
          GH_SLACK_USERNAME_MAP: ${{ secrets.GH_SLACK_USERNAME_MAP }}
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            const script = require('./automations/js/src/count_user_reviewable_prs.js')
            await script({github,context,core})

  send_message:
    needs: analyze-user-prs
    name: Send Slack message
    if: ${{ needs.analyze-user-prs.outputs.pr_count >= 3 }}
    runs-on: ubuntu-latest
    env:
      slack_url: ${{ secrets.SLACK_DM_WEBHOOK_URL }}
      pr_count: ${{ needs.analyze-user-prs.outputs.pr_count }}
      slack_id: ${{ needs.analyze-user-prs.outputs.slack_id }}
    steps:
      - name: Send notification
        id: slack
        uses: slackapi/slack-github-action@1.23.0
        with:
          payload: |
            {
                "user": "'"$slack_id"'",
                "message": "'"$msg"'"
            }
