name: PR label check
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#pr-label-check

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  set_label:
    name: Set labels
    runs-on: ubuntu-latest
    # Only set labels when the PR is created, this should fire `labeled` events
    # that will trigger the checks below.
    if: github.event.action == 'opened'
    steps:
      - name: Trigger remote workflow
        uses: felixp8/dispatch-and-wait@v0.1.0
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
        with:
          owner: WordPress
          repo: openverse
          token: ${{ secrets.ACCESS_TOKEN }}
          event_type: label_pr
          client_payload: ${{ format('{{"pr_url":"{0}"}}', env.PR_URL) }}
          wait_time: 5
          max_time: 60

  check_aspect_label:
    name: Check aspect label
    needs:
      - set_label
    # Check labels only when labels change
    if: github.event.action != 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Check aspect label
        uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: "🚦 status: awaiting triage,💻 aspect: code,📄 aspect: text,🤖 aspect: dx,🕹 aspect: interface,♿️ aspect: a11y"

  check_goal_label:
    name: Check goal label
    needs:
      - set_label
    # Check labels only when labels change
    if: github.event.action != 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Check goal label
        uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: "🚦 status: awaiting triage,🌟 goal: addition,🛠 goal: fix,✨ goal: improvement,🧰 goal: internal improvement"

  check_priority_label:
    name: Check priority label
    needs:
      - set_label
    # Check labels only when labels change
    if: github.event.action != 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Check priority label
        uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: "🚦 status: awaiting triage,🟩 priority: low,🟨 priority: medium,🟧 priority: high,🟥 priority: critical"
