name: Project Thread Update Reminders

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: "0 0 * * *"
  # To allow for manual testing
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: "Dry run"
        required: true
        default: true

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # Ensure that it matches `engines` field in the following files:
          # - `package.json`
          node-version: "16"
          cache: pnpm
          cache-dependency-path: |
            **/pnpm-lock.yaml
            **/.npmrc

      # Install dependencies
      - name: Install JS dependencies
        shell: bash
        run: pnpm install

      - name: Run project thread check
        run: node ./src/project_thread_updates.js
        working-directory: ./automations/js
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
