name: Project Thread Update Reminders

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: "0 0 * * *"
  # To allow for manual testing
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: "Dry run"
        required: true
        default: true

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        with:
          script: |
            const script = require('./automations/js/src/project_thread_updates.js')
            await script({github, core})
